services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=/api/v1
    platform: linux/amd64
    container_name: dalainfo_front
    restart: always
    networks:
      - platforms_net

networks:
  platforms_net:
    external: true
    name: platforms_default
