server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Перенаправляем все запросы на index.html для корректной работы React Router (SPA)
        try_files $uri $uri/ /index.html;
    }

    # Кэширование статических файлов для оптимизации
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        root /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
